import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

mkdirSync("dist/server", { recursive: true });
mkdirSync("dist/.openai", { recursive: true });
copyFileSync(".openai/hosting.json", "dist/.openai/hosting.json");
const html = `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Discord Goal Referee</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b0c10;color:#f4f1ea;font-family:Arial,sans-serif}main{max-width:1060px;margin:auto;padding:42px 22px}.tag{color:#9b8cff;letter-spacing:.13em;font-weight:bold;font-size:12px}h1{font-size:clamp(43px,8vw,78px);line-height:.95;margin:16px 0}h1 span{color:#9b8cff}.lead{max-width:720px;color:#b4b1b7;line-height:1.65;font-size:17px}.summary,.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(205px,1fr));gap:13px}.summary{margin:28px 0}.metric,.card{background:#15161d;border:1px solid #292a35;border-radius:15px;padding:18px}.metric b{display:block;color:#74e4af;font-size:29px}.metric span,.muted{color:#aaa8b1;font-size:13px}.card{margin-top:18px}.person{background:#1b1c24;border-radius:12px;padding:16px}.person h3{margin:8px 0;font-size:21px}.role{color:#74e4af;font-weight:bold}.state{display:inline-block;padding:5px 8px;border-radius:999px;font-size:11px;font-weight:bold;background:#233c31;color:#83efb7}.blocked{background:#48361c;color:#ffd176}.pending{background:#342f54;color:#b9afff}.unknown{background:#39262c;color:#ff9aa7}.bar{height:8px;background:#2b2c35;border-radius:9px;overflow:hidden;margin:12px 0}.bar i{display:block;height:100%;background:#74e4af}.row{display:flex;justify-content:space-between;gap:12px;align-items:center}.file{padding:12px 0;border-bottom:1px solid #2a2b34}.file:last-child{border:0}@media(max-width:520px){main{padding:28px 15px}h1{font-size:47px}}</style></head><body><main>
<p class="tag">DEMO MODE · EVIDENCE BASED</p><h1>Discord Goal<br/><span>Referee</span></h1><p class="lead">프로젝트 대화에서 역할·작업·파일·제약을 분류해 보여주는 데모입니다. 메시지량이 아니라 행동 증거와 확인 상태로 진행률을 판단합니다.</p>
<section class="summary"><div class="metric"><b>4명</b><span>분류된 팀원</span></div><div class="metric"><b>4개</b><span>역할·작업</span></div><div class="metric"><b>1건</b><span>차단 사유</span></div><div class="metric"><b>0건</b><span>자동 완료</span></div></section>
<section class="card"><p class="tag">01 / PEOPLE & ROLES</p><h2>사람별 역할 분류</h2><div class="grid"><article class="person"><span class="state">진행 중</span><h3>도윤</h3><p class="role">개발 · Discord Bot · 배포</p><p class="muted">근거: Bot·GitHub·배포 담당 약속</p></article><article class="person"><span class="state">진행 중</span><h3>서연</h3><p class="role">Fixture · 파일 데이터</p><p class="muted">근거: 가짜 대화 5개·첨부파일</p></article><article class="person"><span class="state blocked">차단됨</span><h3>민재</h3><p class="role">정답셋 · 보안 테스트</p><p class="muted">차단 사유: 14:00 수업</p></article><article class="person"><span class="state pending">검토 대기</span><h3>유나</h3><p class="role">사용자 검증 · 발표</p><p class="muted">근거: 3명 테스트·발표 증거표</p></article></div></section>
<section class="card"><p class="tag">02 / COMPLETENESS</p><h2>작업별 진행률</h2><div class="grid"><article class="person"><div class="row"><b>Bot · 웹 통합</b><span class="state pending">검토 대기</span></div><div class="bar"><i style="width:90%"></i></div><b>90%</b><p class="muted">파일 있음 · 테스트/사람 승인 필요</p></article><article class="person"><div class="row"><b>Fixture 제작</b><span class="state">진행 중</span></div><div class="bar"><i style="width:70%"></i></div><b>70%</b><p class="muted">시나리오·파일 manifest 확인 중</p></article><article class="person"><div class="row"><b>보안 · Goldset</b><span class="state blocked">차단됨</span></div><div class="bar"><i style="width:35%;background:#ffc764"></i></div><b>35%</b><p class="muted">일정 제약 해결 후 재검토</p></article><article class="person"><div class="row"><b>발표 · 사용자 검증</b><span class="state pending">검토 대기</span></div><div class="bar"><i style="width:80%"></i></div><b>80%</b><p class="muted">사용자 피드백과 최종 리허설 대기</p></article></div></section>
<section class="card"><p class="tag">03 / FILES & SAFETY</p><h2>파일 · 근거 · 안전장치</h2><div class="file"><b>demo_v1.zip</b> <span class="muted">· 최신 후보 · checksum d1c24bdcdf94</span></div><div class="file"><b>discord_happy_path_v1.json</b> <span class="muted">· valid · Fixture 근거</span></div><div class="file"><b>security_report.md</b> <span class="muted">· missing · 완료 100% 금지</span></div><p class="muted">허용 채널만 분석 · 근거 없는 담당자 자동 확정 금지 · 위험 행동은 사람 확인</p></section>
</main></body></html>`;
writeFileSync("dist/server/index.js", `const html = ${JSON.stringify(html)}; export default { async fetch() { return new Response(html, { headers: { "content-type": "text/html; charset=utf-8" } }); } };\n`);
